# Global settings.
source: src
destination: src/_site
timezone: Europe/London

# Site settings.
title: kieranbamforth.me
description: A braindump, mostly.
url: http://www.kieranbamforth.me
baseurl: /blog
permalink: /:categories/:title

# Contact / handles.
email: hello@kieranbamforth.me
twitter_username: kieran_bamforth
github_username:  kieran-bamforth

# Build settings.
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
