# Global settings.
source: src
destination: src/_site
timezone: Europe/London

# Site settings.
title: kieranbamforth.me
description: A braindump, mostly.
url: https://www.kieranbamforth.me
permalink: /:categories/:title

# Jekyll paginate
paginate: 25

# Build settings.
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

# Chalk settings.
rss_enabled: true
name: kieranbamforth.me
social:
    github: kieran-bamforth
    twitter: kieran_bamforth
    email: hello@kieranbamforth.me
    linkedin: kieran-bamforth
ga_analytics: UA-58001717-3
scrollappear_enabled: false
local_fonts: true
