# Global settings.
source: src
destination: src/_site
timezone: Europe/London

# Site settings.
title: kieranbamforth.me
description: A braindump, mostly.
url: http://www.kieranbamforth.me
baseurl: /blog
permalink: /:categories/:title:output_ext

# Contact / handles.
email: hello@kieranbamforth.me
twitter_username: kieran_bamforth
github_username:  kieran-bamforth

# Build settings.
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

# Chalk settings.
rss_enabled: false
name: kieranbamforth.me
social:
    github: kieran-bamforth
    twitter: kieran_bamforth
    email: hello@kieranbamforth.me
    linkedin: kieran-bamforth
ga_analytics: UA-58001717-3
scrollappear_enabled: false
